version: 2
jobs:
  test:
    docker:
      - image: redis:alpine
      - image: memcached:alpine
    parallelism: 1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: sudo apt-get update --allow-releaseinfo-change
      - run:
          name: Run specs for redis cache store
          environment:
            TEST_CACHE_STORE: redis_cache_store
          command: bundle exec rspec spec/
      - run:
          name: Run specs for memcached cache store
          environment:
            TEST_CACHE_STORE: mem_cache_store
          command: bundle exec rspec spec/
      - run:
          name: Run specs for in-memory cache store
          command: bundle exec rspec spec/
workflows:
  version: 2
  test:
    jobs:
      - test
